/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData muscle_up = IconData(0xea48, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell = IconData(0xf44b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData sport_gym_cycling = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yoga_bridge = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fitness_dumbbell = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yoga_standing_forward_fold_pose = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wpbeginner = IconData(0xf297, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medium_m = IconData(0xf3c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
